# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

image: painless/tox

.lint:
  stage: lint
  only:
  - merge_request
  - master

.test:
  stage: test
  only:
  - merge_request
  - master

stages:
- lint
- test

flake8:
  extends: .lint
  script: tox -e flake8
  allow_failure: true

pylint:
  extends: .lint
  script: tox -e pylint
  allow_failure: true

safety:
  extends: .lint
  script: tox -e safety

bandit:
  extends: .lint
  script: tox -e bandit
  allow_failure: true

readme:
  extends: .lint
  script: tox -e readme

py36:
  extends: .test
  script: tox -e py36

py37:
  extends: .test
  script: tox -e py37

py38:
  extends: .test
  script: tox -e py38
