name: Pull Request
on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_flake8
          - lint_pylint
          - lint_bandit
          - test_py36
          - test_py37
          - test_py38
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Poetry
      run: |
        pip install poetry tox
    - name: Run ${{ matrix.command }}
      run: make ${{ matrix.command }}
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Docs
      run: make check
    - name: Compile Docs
      run: make docs
  build:
    needs:
    - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      env:
        VERSION: v0.0.0+test
      run: make docker
  build-component-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build component testing image
      run: make docker-component-test
      env:
        VERSION: test
