name: Test
on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_flake8
          - lint_pylint
          - lint_safety
          - lint_bandit
          - lint_readme
          - test_py36
          - test_py37
          - test_py38
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Pipenv
      run: |
        pip install pipenv tox
    - name: Flake8
      run: make ${{ matrix.command }}

    - name: Run tests on Python 3.8
      run: make test_py38
  build:
    needs:
    - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: make docker
